import { makeStyles } from "@mui/styles";
import {
  BLACK_COLOR,
  BLUE_COLOR,
  CLICKED_BLUE_BUTTON,
  CLICKED_GREEN_BUTTON,
  CLICKED_ORANGE_BUTTON,
  CLICKED_RED_BUTTON,
  FILTER_BUTTON,
  GREEN_COLOR,
  ORANGE_COLOR,
  RED_COLOR,
  SHADOW_BLUE_BUTTON,
  SHADOW_GREEN_BUTTON,
  SHADOW_ON_CLICK_BLUE_BUTTON,
  SHADOW_ORANGE_BUTTON,
  SHADOW_RED_BUTTON,
  WHITE_COLOR,
} from "../../../helpers/colorsConstant";

const useStyles = makeStyles({
  toAll: {
    marginLeft: 1142,
    display: "inline-block",
    textOverflow: "Ellipsis",
    flexWrap: "wrap",
    position: "relative",
    top: 50,
    "@media (max-width: 1500px)": {
      marginLeft: "70%",
      alignItems: "center",
      paddingBottom: "2px",
    },
    "@media  (max-width:1200px)": {
      alignItems: "center !important",
      marginLeft: 0,
      left: "34%",
      top: -5,
    },
    "@media  (max-width:1135px)": {
      alignItems: "center !important",
      marginLeft: 0,
      left: 0,
      top: -5,
    },
    "@media  (max-width:1124px)": {
      alignItems: "center !important",
      marginLeft: 0,
      left: 0,
      top: -5,
    },
    "@media  (max-width:1115px)": {
      alignItems: "center",
      marginLeft: 0,
      left: 0,
      top: -5,
    },
    "@media  (max-width:1114px)": {
      alignItems: "center",
      marginLeft: 0,
      left: 0,
      top: -5,
    },
    "@media  (max-width:1097px)": {
      alignItems: "center",
      marginLeft: 0,
    },
  },

  redButtonClicked: {
    background: CLICKED_RED_BUTTON,
    border: 0,
    borderRadius: 3,
    fontWeight: "bolder !important",
    boxShadow: SHADOW_RED_BUTTON,
    color: WHITE_COLOR,
    height: 53,
    width: 80,
  },
  redButtonNotClicked: {
    background: FILTER_BUTTON,
    borderColor: RED_COLOR + " !important",
    borderWidth: "1px !important",
    borderStyle: "solid !important",
    borderRadius: 3,
    fontWeight: "bolder !important",
    boxShadow: SHADOW_RED_BUTTON,
    color: RED_COLOR + " !important",
    height: 53,
    width: 80,
  },
  greenButtonClicked: {
    background: CLICKED_GREEN_BUTTON,
    border: 0,
    borderRadius: 3,
    fontWeight: "bolder !important",
    boxShadow: SHADOW_GREEN_BUTTON,
    color: WHITE_COLOR,
    height: 53,
    width: 80,
  },
  greenButtonNotClicked: {
    background: FILTER_BUTTON,
    borderColor: GREEN_COLOR + " !important",
    borderWidth: "1px !important",
    borderStyle: "solid !important",
    borderRadius: 3,
    fontWeight: "bolder !important",
    boxShadow: SHADOW_GREEN_BUTTON,
    color: GREEN_COLOR + " !important",
    height: 53,
    width: 80,
  },
  blueButtonClicked: {
    background: CLICKED_BLUE_BUTTON,
    border: 0,
    borderRadius: 3,
    boxShadow: SHADOW_ON_CLICK_BLUE_BUTTON,
    color: WHITE_COLOR,
    fontWeight: "bolder !important",
    height: 53,
    width: 80,
  },
  blueButtonNotClicked: {
    background: FILTER_BUTTON,
    borderColor: BLUE_COLOR + " !important",
    borderWidth: "1px !important",
    borderStyle: "solid !important",
    borderRadius: 3,
    fontWeight: "bolder !important",
    boxShadow: SHADOW_BLUE_BUTTON,
    color: BLUE_COLOR + " !important",
    height: 53,
    width: 80,
  },
  orangeButtonClicked: {
    background: CLICKED_ORANGE_BUTTON,
    border: 0,
    borderRadius: 3,
    fontWeight: "bolder !important",
    boxShadow: SHADOW_ORANGE_BUTTON,
    color: WHITE_COLOR,
    height: 53,
    width: 80,
  },
  orangeButtonNotClicked: {
    background: FILTER_BUTTON,
    borderColor: ORANGE_COLOR + " !important",
    borderWidth: "1px !important",
    borderStyle: "solid !important",
    borderRadius: 3,
    fontWeight: "bolder !important",
    boxShadow: SHADOW_ORANGE_BUTTON,
    color: ORANGE_COLOR + " !important",
    height: 53,
    width: 80,
  },
  divNumber: {
    color: BLACK_COLOR,
    display: "block",
    width: 50,
    height: 20,
    margin: 1,
    backgroundColor: WHITE_COLOR,
    borderRadius: 10,
    fontWeight: "bolder",
  },
  buttonGroup: {
    flexWrap: "wrap",
    "@media (max-width: 1500px)": {
      display: "center !important",
      alignItems: "center !important",
      justifyContent: "center",
    },
  },
});
export default useStyles;
